# Site settings
title: Maxim Tatarchenko
email: m.tatarchenko@yahoo.com
url: http://mtatarchenko.github.io/
description: "My personal website."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Maxim Tatarchenko

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/maxim.tatarchenko.1
  - title: github
    url: https://github.com/mtatarchenko/
  - title: linkedin
  	url: https://de.linkedin.com/in/maximtatarchenko

# Build settings
markdown: kramdown
permalink: pretty
